// Regenerates src/test/seed.fixture.ts from the raw scaffold patents in
// scripts/seed-source/, by running them through the real editor.
//
//   npm run normalise-seed
//
// Why this exists: the scaffold stored pretty-printed full HTML documents, but
// TipTap's getHTML() emits a collapsed single-line body fragment. Storing the
// raw shape means the parser sees one shape before the first save and another
// after it. The normalised constant is what server/app/data.py must store, and
// server/tests/test_seed_fixture.py asserts the two agree.
//
// Produced by running the editor rather than by hand: hand-collapsing 3 KB of
// HTML is exactly the near-miss that costs a day.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { JSDOM } from "jsdom";

const here = dirname(fileURLToPath(import.meta.url));

// TipTap/ProseMirror read these off the global scope at import time, so the DOM
// has to exist before @tiptap/core is loaded.
const dom = new JSDOM("<!DOCTYPE html><body></body>");
for (const name of ["window", "document", "navigator", "DOMParser", "Element", "Node"]) {
  Object.defineProperty(globalThis, name, {
    value: name === "window" ? dom.window : dom.window[name],
    configurable: true,
    writable: true,
  });
}

const { Editor } = await import("@tiptap/core");
const { default: StarterKit } = await import("@tiptap/starter-kit");

const normalise = (raw) => {
  const editor = new Editor({ content: raw, extensions: [StarterKit] });
  const html = editor.getHTML();
  editor.destroy();
  return html;
};

const title = (raw) => raw.match(/<title>([\s\S]*?)<\/title>/)[1].trim();

const sources = ["patent-1.html", "patent-2.html"].map((file) =>
  readFileSync(resolve(here, "seed-source", file), "utf8"),
);

const lines = [
  "// GENERATED by scripts/normalise_seed.mjs — do not edit by hand.",
  "// server/app/data.py must match; server/tests/test_seed_fixture.py asserts it.",
  ...sources.map((raw, i) => `export const SEED_${i + 1} = ${JSON.stringify(normalise(raw))};`),
  "",
].join("\n");

writeFileSync(resolve(here, "..", "src", "test", "seed.fixture.ts"), lines);

// The titles live on Document.title in data.py; printed so a regeneration shows
// whether they moved.
sources.forEach((raw, i) => console.log(`SEED_${i + 1} title: ${JSON.stringify(title(raw))}`));
console.log("wrote src/test/seed.fixture.ts");
